- hosts: localhost

  tasks:

    - name: Disable recent files in Nautilus
      dconf:
        key: "/org/gnome/desktop/privacy/remember-recent-files"
        value: "false"

    - name: Enable Night Light in Gnome
      dconf:
        key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
        value: "true"

    - name: Set Tallinn coordinates for Night Light
      dconf:
        key: "/org/gnome/settings-daemon/plugins/color/night-light-last-coordinates"
        value: "(59.441999280057594, 24.732299999999999)"

    - name: Set Night Light Temperature
      dconf:
        key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature"
        value: "uint32 2700"

    - name: Schedule Night Light from sunset to sunrise
      dconf:
        key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic"
        value: "true"
