- hosts: localhost
  tasks:
    - name: Install common packages
      become: true
      package:
        name:
          - fzf
          - ansible-lint
          - asciidoctor
          - calibre
          - keepassxc
          - ifuse
          - gthumb
          - aria2
          - hugo
          - ulauncher
        state: present

    - name: Uninstall common packages
      become: true
      package:
        name:
          - evolution
          - libreoffice-core
          - libreofficekit
          - shotwell
          - fira-code-fonts
          - salt
          - zoom
        state: absent
