- hosts: localhost
  tasks:
    - name: Install common packages
      become: true
      package:
        name:
          - fzf
          - ansible-lint
          - asciidoctor
          - calibre
          - keepassxc
          - ifuse
          - gthumb
          - aria2
        state: present

    - name: Uninstall common packages
      become: true
      package:
        name:
          - evolution
          - libreoffice-core
          - libreofficekit
          - shotwell
          - fira-code-fonts
        state: absent

    - name: Install packages by a direct RPM
      become: true
      package:
        name:
          - https://go.skype.com/skypeforlinux-64.rpm
          - https://zoom.us/client/latest/zoom_x86_64.rpm
        state: present
