- hosts: localhost
  tasks:
    - name: Install common packages
      become: true
      package: name={{ item }} state=present
      with_items:
        - fzf
        - ansible-lint
        - asciidoctor
        - calibre

    - name: Uninstall common packages
      become: true
      package: name={{ item }} state=absent
      with_items:
        - evolution
        - libreoffice-core
        - libreofficekit
