- hosts: localhost
  tasks:
    - name: Install common packages
      become: true
      package: name={{ item }} state=present
      with_items:
        - fzf
        - ansible-lint
        - asciidoctor
        - calibre
        - keepassxc

    - name: Uninstall common packages
      become: true
      package: name={{ item }} state=absent
      with_items:
        - evolution
        - libreoffice-core
        - libreofficekit

    - name: Install Flatpak apps
      flatpak:
        name: com.spotify.Client

    - name: Install packages by a direct RPM
      become: true
      package: name={{ item }} state=present
      with_items:
        - https://go.skype.com/skypeforlinux-64.rpm
        - https://zoom.us/client/latest/zoom_x86_64.rpm
