- hosts: localhost
  tasks:

    - name: install packages from rpmfusion repo
      become: true
      package: name={{ item }} state=present
      with_items:
        - fuse-exfat
        - ffmpeg-libs
        - compat-ffmpeg28

    - name: Remove unnecessary repositories
      become: true
      command: dnf config-manager --set-disabled Emulators_Wine_Fedora tvinternal_dev tvinternal_it evana-fira-code-fonts
