- hosts: localhost
  tasks:

    - name: Install Spotify flatpak
      flatpak:
        name: com.spotify.Client

    - name: Install Telegram flatpak
      flatpak:
        name: org.telegram.desktop

    - name: Install VLC flatpak
      flatpak:
        name: org.videolan.VLC

    - name: Install MusicBrainz Picard
      flatpak:
        name: org.musicbrainz.Picard

    - name: Install DBeaver - Universal Database Manager
      flatpak:
        name: io.dbeaver.DBeaverCommunity

    - name: Install Gimp - photo and image editor
      flatpak:
        name: org.gimp.GIMP

    - name: Install Zoom
      flatpak:
        name: us.zoom.Zoom
