- hosts: localhost
  tasks:

    - name: Install Spotify flatpak
      flatpak:
        name: com.spotify.Client

    - name: Install Telegram flatpak
      flatpak:
        name: org.telegram.desktop

    - name: Install VLC flatpak
      flatpak:
        name: org.videolan.VLC

    - name: Install Zoom
      flatpak:
        name: us.zoom.Zoom

    - name: Install Bitwarden
      flatpak:
        name: com.bitwarden.desktop

    - name: Install WhatsApp desktop
      flatpak:
        name: io.github.mimbrero.WhatsAppDesktop

    - name: Remove MusicBrainz Picard
      flatpak:
        name: org.musicbrainz.Picard
        state: absent

    - name: Remove DBeaver - Universal Database Manager
      flatpak:
        name: io.dbeaver.DBeaverCommunity
        state: absent

    - name: Remove Gimp - photo and image editor
      flatpak:
        name: org.gimp.GIMP
        state: absent

    - name: Install Viber
      flatpak:
        name: com.viber.Viber
