- hosts: localhost
  vars:
    fish_init_dir: "{{ ansible_env.HOME }}/.config/fish/conf.d"

  tasks:

    - name: Create directory for initialization files
      file:
        path: "{{ fish_init_dir }}"
        state: directory

    - name: Create symbolic link to configuration file for SDKMAN tool
      file:
        src: "{{ playbook_dir }}/sdkman.fish"
        dest: "{{ fish_init_dir }}/sdkman.fish"
        state: link
